### ISSUE TITLE
SvelteKit: .env not being detected

### ISSUE THREAD

**Issue by merryface** [directus/examples#94] opened 2022-04-15 17:24 UTC
I followed the instructions using [this article](https://directus.io/guides/get-started-building-a-sveltekit-website-with-directus/), ensuring that:

1. `npm install` had successfully run in both the `directus` directory and `sveltekit` directory
2. `.env.example` was copied and the copy renamed to `.env`, ensuring that no changes were made.
3. Running both projects using `npm run dev` for the sveltekit and `npx directus start` in the appropriate directories

I can login succesfully into the Directus admin panel. The directus-sveltekit's 404 appears on the homepage of the frontend, and the following message appears in the terminal for the sveltekit directory:

```bash
Unable to connect to the Directus instance. Make sure the .env file is present and the VITE_DIRECTUS_URL variable is pointing the correct URL.
```

Restarting both projects has failed to yield different results*, no matter which one I start first.
I have double checked that I have not changed the `.env` is indeed saved as `.env`, that it is in the root of the `sveltekit` directory, and that the URL set is 'http://localhost:8055'.

No other errors that I can find.

*edit: for clarity

**Comment by merryface** [comment] 2022-04-15 18:11
In my continued attempts to fix this, I have noticed the following in the terminal when running Directus:

```basg
19:08:40 ⚠️  Spatialite isn't installed. Geometry type support will be limited.
19:08:40 ⚠️  Database migrations have not all been run
```

**Comment by azrikahar** [comment] 2022-04-18 07:40
I can't seem to reproduce this on my end:

https://user-images.githubusercontent.com/42867097/163773163-728b05de-fb85-4cca-927d-5fbd477d2bcd.mp4

Is the Sveltekit version in your local installation the same as seen in my clip above? In addition, would you mind trying the steps shown below so that we can confirm whether `VITE_DIRECTUS_URL` is working in your setup:

(It should log the URL out in your console)

https://user-images.githubusercontent.com/42867097/163774062-7e66f796-e21a-4681-aae4-4305fba509cc.mp4


> In my continued attempts to fix this, I have noticed the following in the terminal when running Directus:
> 
> ```
> 19:08:40 ⚠️  Spatialite isn't installed. Geometry type support will be limited.
> 19:08:40 ⚠️  Database migrations have not all been run
> ```

The first spatialite warning is working as intended, as the example does indeed do not include it 👍. As for the second line, the example was bumped to `v9.7.0` via dependabot but the database file itself has run the migrations. It should be updated, but I'm not sure if it's related here as it doesn't seem to cause any issue when I tested it as shown above.

**Comment by azrikahar** [comment] 2022-06-14 09:20
Granted I've yet to be able to reproduce this issue after testing locally, I just did a full upgrade to every examples including Directus and SvelteKit. It is still working on my end after the upgrade, so I'll close this for now. If you are still facing the same issue after the new update, do let us know and we'll try to investigate further 👍

**Closed** 2022-06-14 09:21 UTC
